apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: prelivegov-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-prod
        namespace: flux-prod
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: aws
        cloudNativeServices: false
        kubernetesUrl: https://85CE266964E8B1DB527EB8913F2615B3.gr7.ap-southeast-1.eks.amazonaws.com
      vault:
        type: hashicorp
        network: fabric
        address: http://vault.vault.svc:8200
        authPath: prodprelivegov
        secretEngine: secretsv2
        secretPrefix: "data/prodprelivegov"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: org4proxy.hlf.doconchain.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:latest
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: prelivegov-admin
      adminPassword: prelivegov-adminpw
      subject: "/C=US/ST=Boston/L=Boston/O=PLGov"
      clusterIpPort: 7054

    labels:
      service:
        - example1: example2
      pvc:
      deployment:
