apiVersion: batch/v1
kind: Job
metadata:
  name: instextcc-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app: instextcc-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
    app.kubernetes.io/name: instextcc-{{ $.Values.chaincode.name }}{{ $.Values.chaincode.version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: instextcc-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}
        app.kubernetes.io/name: instextcc-{{ $.Values.chaincode.name }}{{ $.Values.chaincode.version }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ $.Values.global.serviceAccountName }}
      {{- if .Values.vault.imagesecretname }}
      imagePullSecrets:
        - name: {{ $.Values.vault.imagesecretname }}
      {{- end }}
      volumes:
      {{ if .Values.global.vault.tls  }}
      - name: vaultca
        secret:
          secretName: {{ $.Values.global.vault.tls }}
          items:
          - key: ca.crt.pem
            path: ca-certificates.crt
      {{ end  }}
      - name: certificates
        emptyDir:
          medium: Memory
      - name: chaincodepackage
        emptyDir:
          medium: Memory
      - name: scripts-volume
        configMap:
          name: bevel-vault-script
      initContainers:
      - name: certificates-init
        image: {{ $.Values.metadata.images.alpineutils }}
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: {{ $.Values.global.vault.address }}
        - name: KUBERNETES_AUTH_PATH
          value: {{ $.Values.global.vault.authPath }}
        - name: VAULT_APP_ROLE
          value: {{ $.Values.global.vault.role }}
        - name: VAULT_CHAINCODE_PEER_SECRET_PREFIX
          value: {{ $.Values.vault.peerschaincodetlssecretprefix }}
        - name: VAULT_PEER_SECRET_PREFIX
          value: "{{ $.Values.vault.adminsecretprefix }}"
        - name: CHAINCODE_NAME
          value: "{{ $.Values.chaincode.name }}"
        - name: MOUNT_PATH
          value: /secret
        - name: NETWORK_VERSION
          value: "{{ $.Values.global.version }}"
        - name: CHAINCODE_TLS_DISABLED
          value: "{{ $.Values.chaincode.tls_disabled }}"
        - name: VAULT_TYPE
          value: "{{ $.Values.global.vault.type }}"
        command: ["sh", "-c"]
        args:
        - |-
          #!/usr/bin/env sh
          . /scripts/bevel-vault.sh

          # Calling a function to retrieve the vault token.
          vaultBevelFunc "init"

          echo "Getting MSP certificates from Vault."
          vaultBevelFunc "readJson" "${VAULT_PEER_SECRET_PREFIX}-msp"

          ADMINCERT=$(echo ${VAULT_SECRET} | jq -r '.["admincerts"]')
          CACERTS=$(echo ${VAULT_SECRET} | jq -r '.["cacerts"]')
          KEYSTORE=$(echo ${VAULT_SECRET} | jq -r '.["keystore"]')
          SIGNCERTS=$(echo ${VAULT_SECRET} | jq -r '.["signcerts"]')
          TLSCACERTS=$(echo ${VAULT_SECRET} | jq -r '.["tlscacerts"]')

          OUTPUT_PATH="${MOUNT_PATH}/admin/msp"
          mkdir -p ${OUTPUT_PATH}/admincerts
          mkdir -p ${OUTPUT_PATH}/cacerts
          mkdir -p ${OUTPUT_PATH}/keystore
          mkdir -p ${OUTPUT_PATH}/signcerts
          mkdir -p ${OUTPUT_PATH}/tlscacerts

          echo "${ADMINCERT}" >> ${OUTPUT_PATH}/admincerts/admin.crt
          echo "${CACERTS}" >> ${OUTPUT_PATH}/cacerts/ca.crt
          echo "${KEYSTORE}" >> ${OUTPUT_PATH}/keystore/server.key
          echo "${SIGNCERTS}" >> ${OUTPUT_PATH}/signcerts/server.crt
          echo "${TLSCACERTS}" >> ${OUTPUT_PATH}/tlscacerts/tlsca.crt

          if [ "${CHAINCODE_TLS_DISABLED}" == "false" ]; then
            echo "Getting chaincode certificates from Vault."
            vaultBevelFunc "readJson" "${VAULT_CHAINCODE_PEER_SECRET_PREFIX}/peers-${CHAINCODE_NAME}-tls"

            if [ "$SECRETS_AVAILABLE" != "yes" ]; then
                echo "Peer-Chaincode TLS certificates not found in ${VAULT_CHAINCODE_PEER_SECRET_PREFIX}/peers-${CHAINCODE_NAME}-tls"
                exit 1
            fi
    
            CACERT=$(echo ${VAULT_SECRET} | jq -r '.["ca_crt"]')
            CLIENT_CERT=$(echo ${VAULT_SECRET} | jq -r '.["client_crt"]')
            CLIENT_KEY=$(echo ${VAULT_SECRET} | jq -r '.["client_key"]')

            OUTPUT_PATH="${MOUNT_PATH}/chaincode"
            mkdir -p ${OUTPUT_PATH}
            echo "${CACERT}" >> ${OUTPUT_PATH}/ca.crt
            echo "${CLIENT_CERT}" >> ${OUTPUT_PATH}/client.crt
            echo "${CLIENT_KEY}" >> ${OUTPUT_PATH}/client.key
          fi
        volumeMounts:
        {{ if .Values.global.vault.tls  }}
        - name: vaultca
          mountPath: "/etc/ssl/certs/"
          readOnly: true
        {{ end }}
        - name: certificates
          mountPath: /secret
        - name: scripts-volume
          mountPath: /scripts/bevel-vault.sh
          subPath: bevel-vault.sh
      - name: package-init
        image: {{ $.Values.metadata.images.alpineutils }}
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: {{ $.Values.global.vault.address }}
        - name: KUBERNETES_AUTH_PATH
          value: {{ $.Values.global.vault.authPath }}
        - name: VAULT_APP_ROLE
          value: {{ $.Values.global.vault.role }}
        - name: VAULT_CHAINCODE_PACKAGE_PREFIX
          value: {{ $.Values.vault.chaincodepackageprefix }}
        - name: CHAINCODE_NAME
          value: "{{ $.Values.chaincode.name }}"
        - name: CHAINCODE_ADDR
          value: "{{ $.Values.chaincode.address }}"
        - name: CHAINCODE_VERSION
          value: "{{ $.Values.chaincode.version }}"
        - name: CHAINCODE_TLS_DISABLED
          value: "{{ $.Values.chaincode.tls_disabled }}"
        {{- if not $.Values.chaincode.tls_disabled }}
        - name: CHAINCODE_SECRET_MOUNT_PATH
          value: /secret/chaincode
        {{- end }}
        - name: CHAINCODE_MOUNT_PATH
          value: /chaincodepackage
        - name: VAULT_TYPE
          value: "{{ $.Values.global.vault.type }}"
        command: ["sh", "-c"]
        args:
        - |-
          #!/usr/bin/env sh
          . /scripts/bevel-vault.sh

          # Calling a function to retrieve the vault token.
          vaultBevelFunc "init"

          # Use the peer default external builder if the building path
          # is empty.
          kubectl -n {{ $.Values.metadata.namespace }} exec pods/fabric-peernode-{{ $.Values.peer.name }}-0 -c {{ $.Values.peer.name }} -- bash -c '
          BUILDER_PATH=/var/hyperledger/production/buildpacks/sampleBuilder
          DEFAULT_BUILDER_PATH=/opt/hyperledger/ccaas_builder

          stat ${BUILDER_PATH} > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            mkdir -p ${BUILDER_PATH}
            cp -r ${DEFAULT_BUILDER_PATH}/bin ${BUILDER_PATH}
          fi
          '

          VAULT_CHAINCODE_PACKAGE="${VAULT_CHAINCODE_PACKAGE_PREFIX}/${CHAINCODE_NAME}/package/v${CHAINCODE_VERSION}"
          echo "Getting Package Base64 from Vault in ${VAULT_CHAINCODE_PACKAGE}"
          vaultBevelFunc "readJson" "${VAULT_CHAINCODE_PACKAGE}"
          if [ "$SECRETS_AVAILABLE" = "yes" ]; then
            echo "Chaincode package found on vault. Skipping package generation."
            PACKAGE_BASE64=$(echo ${VAULT_SECRET} | jq -r '.["package-base64"]')
            echo ${PACKAGE_BASE64} | base64 -d > ${CHAINCODE_MOUNT_PATH}/${CHAINCODE_NAME}_${CHAINCODE_VERSION}.tgz
            exit 0
          fi

          echo "Package Base64 not found in ${VAULT_CHAINCODE_PACKAGE}"
          echo "Building the package for the chaincode"

          PACKAGE_NAME=${CHAINCODE_NAME}_${CHAINCODE_VERSION}

          if [ "${CHAINCODE_TLS_DISABLED}" == "false" ]; then
            echo "Packaging external chaincode. TLS enabled."
            CA_CERT="$(cat ${CHAINCODE_SECRET_MOUNT_PATH}/ca.crt)"
            CLIENT_CERT="$(cat ${CHAINCODE_SECRET_MOUNT_PATH}/client.crt)"
            CLIENT_KEY="$(cat ${CHAINCODE_SECRET_MOUNT_PATH}/client.key)"

            echo '{}' | jq --arg cc_addr "${CHAINCODE_ADDR}" \
              --arg c_key "${CLIENT_KEY}" \
              --arg c_crt "${CLIENT_CERT}" \
              --arg ca_crt "${CA_CERT}" \
              '{"address": $cc_addr, "dial_timeout":"10s", "tls_required":true, "client_auth_required":true, "client_key":$c_key, "client_cert":$c_crt, "root_cert":$ca_crt}' > connection.json
          else
            echo Packaging external chaincode. No tls.
            echo '{"address":"'${CHAINCODE_ADDR}'","dial_timeout":"10s","tls_required":false,"client_auth_required":false,"client_key":"","client_cert":"","root_cert":""}' > connection.json
          fi

          echo '{"path":"","type":"ccaas","label":"'${PACKAGE_NAME}'"}' > metadata.json

          tar cfz code.tar.gz connection.json;
          tar cfz ${CHAINCODE_MOUNT_PATH}/${PACKAGE_NAME}.tgz code.tar.gz metadata.json;

          PACKAGE_BASE64=$(base64 -w 0 ${CHAINCODE_MOUNT_PATH}/${PACKAGE_NAME}.tgz)

          # see https://github.com/hyperledger/fabric/blob/e1e8e2e52aa4fc543360d245fe6554a0eaf81183/core/chaincode/persistence/persistence.go#L246-L249
          PACKAGE_ID="${CHAINCODE_NAME}_${CHAINCODE_VERSION}:$(sha256sum ${CHAINCODE_MOUNT_PATH}/${PACKAGE_NAME}.tgz | awk '{print $1}')"
          echo "Package ID: ${PACKAGE_ID}"

          echo "
          {
            \"data\":
              {
                \"package-base64\": \"${PACKAGE_BASE64}\",
                \"package-id\": \"${PACKAGE_ID}\"

              }
          }" > payload.json
          cat payload.json
          vaultBevelFunc "write" "${VAULT_CHAINCODE_PACKAGE}" "payload.json"

          kubectl -n {{ $.Values.metadata.namespace }} create configmap {{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}-package-id --from-literal=package-id=${PACKAGE_ID}
        volumeMounts:
        {{ if .Values.global.vault.tls  }}
        - name: vaultca
          mountPath: "/etc/ssl/certs/"
          readOnly: true
        {{ end }}
        - name: chaincodepackage
          mountPath: /chaincodepackage
          readOnly: false
        - name: certificates
          mountPath: /secret
        - name: scripts-volume
          mountPath: /scripts/bevel-vault.sh
          subPath: bevel-vault.sh
      containers:
      - name: instextcc
        image: {{ $.Values.metadata.images.fabrictools }}
        imagePullPolicy: Always
        stdin: true
        tty: true
        command: ["sh", "-c"]
        args:
        - |-
          #!/bin/bash sh

          # validate if chaincode is installed
          INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
          if [ -n "${INSTALLED}" ]
          then
            echo "chaincode ${CHAINCODE_NAME}_${CHAINCODE_VERSION} is installed, skipping... "
            exit 0
          fi
          ## Installing Chaincode
          peer lifecycle chaincode install ${CHAINCODE_MOUNT_PATH}/${CHAINCODE_NAME}_${CHAINCODE_VERSION}.tgz
          echo "Chaincode installed for Fabric v.2.X"
          #query installed
          echo "peer query installed"
          peer lifecycle chaincode queryinstalled
          ## Check if chaincode got installed 
          echo "Checking if chaincode was installed"
          INSTALLED=$(peer lifecycle chaincode queryinstalled -O json | jq '.installed_chaincodes?' | \
            jq --arg CCLABEL "${CHAINCODE_NAME}_${CHAINCODE_VERSION}" '.[]? | select(.label==$CCLABEL)')
          if ! [ -n "${INSTALLED}" ]
          then
            echo "Error while installing chaincode, exiting.."
            exit 1
          fi
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: {{ $.Values.peer.loglevel }}
        - name: CORE_PEER_ID
          value: {{ $.Values.peer.name }}.{{ $.Values.metadata.namespace }}
        - name: CORE_PEER_ADDRESS
          value: {{ $.Values.peer.address }}
        - name: CORE_PEER_LOCALMSPID
          value: {{ $.Values.peer.localmspid }}
        - name: CORE_PEER_TLS_ENABLED
          value: "{{ $.Values.peer.tlsstatus }}"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/cacerts/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp
        - name: CHAINCODE_CERTS_PATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/crypto/chaincode
        - name: CHAINCODE_NAME
          value: "{{ $.Values.chaincode.name }}"
        - name: CHAINCODE_TLS_DISABLED
          value: "{{ $.Values.chaincode.tls_disabled }}"
        - name: CHAINCODE_ADDR
          value: "{{ $.Values.chaincode.address }}"
        - name: CHAINCODE_MAINDIR
          value: "{{ $.Values.chaincode.maindirectory }}"
        - name: CHAINCODE_VERSION
          value: "{{ $.Values.chaincode.version }}"
        - name: CORE_CHAINCODE_BUILDER
          value: "{{ $.Values.chaincode.builder }}"
        - name: NETWORK_VERSION
          value: "{{ $.Values.global.version }}"
        - name: CC_RUNTIME_LANGUAGE
          value: "{{ $.Values.chaincode.lang }}"
        - name: CHAINCODE_MOUNT_PATH
          value: /chaincodepackage
        volumeMounts:
        - name: certificates
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/crypto
          readOnly: true
        - name: chaincodepackage
          mountPath: /chaincodepackage
          readOnly: true
