###########################################################################################
# Track how many peers in the org installed each chaincode.
# This is used to generate the chaincode crypto artifacts only once per organization.
- name: Track how many peers in the org installed each chaincode
  set_fact:
    install_count: "{{ {} }}"

# Install the external chaincode details
- name: Install the external chaincode details
  include_tasks: nested_main.yaml
  vars:
    chaincode_name: "{{ peer.chaincode.name | lower }}"
    chaincode_version: "{{ peer.chaincode.version }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when:
    - peer.chaincodes is defined
